const WATER_HEIGHT = 0.4
const MOUNTAIN_HEIGHT = 0.8
const TILE_SIZE = 16

const IS_HEIGHT_WALKABLE = (height: number) => height > WATER_HEIGHT && height < MOUNTAIN_HEIGHT

export { WATER_HEIGHT, MOUNTAIN_HEIGHT, TILE_SIZE, IS_HEIGHT_WALKABLE }